/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Platform.CSharp.Model;
using MX.Platform.CSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Platform.CSharp.Test.Model
{
    /// <summary>
    ///  Class for testing CreditCardProductResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreditCardProductResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreditCardProductResponse
        //private CreditCardProductResponse instance;

        public CreditCardProductResponseTests()
        {
            // TODO uncomment below to create an instance of CreditCardProductResponse
            //instance = new CreditCardProductResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreditCardProductResponse
        /// </summary>
        [Fact]
        public void CreditCardProductResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreditCardProductResponse
            //Assert.IsType<CreditCardProductResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CreditCardProduct'
        /// </summary>
        [Fact]
        public void CreditCardProductTest()
        {
            // TODO unit test for the property 'CreditCardProduct'
        }
    }
}
