/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Platform.CSharp.Model;
using MX.Platform.CSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Platform.CSharp.Test.Model
{
    /// <summary>
    ///  Class for testing CreditCardProduct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreditCardProductTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreditCardProduct
        //private CreditCardProduct instance;

        public CreditCardProductTests()
        {
            // TODO uncomment below to create an instance of CreditCardProduct
            //instance = new CreditCardProduct();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreditCardProduct
        /// </summary>
        [Fact]
        public void CreditCardProductInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreditCardProduct
            //Assert.IsType<CreditCardProduct>(instance);
        }

        /// <summary>
        /// Test the property 'AnnualFee'
        /// </summary>
        [Fact]
        public void AnnualFeeTest()
        {
            // TODO unit test for the property 'AnnualFee'
        }

        /// <summary>
        /// Test the property 'DurationOfIntroductoryRateOnBalanceTransfer'
        /// </summary>
        [Fact]
        public void DurationOfIntroductoryRateOnBalanceTransferTest()
        {
            // TODO unit test for the property 'DurationOfIntroductoryRateOnBalanceTransfer'
        }

        /// <summary>
        /// Test the property 'DurationOfIntroductoryRateOnPurchases'
        /// </summary>
        [Fact]
        public void DurationOfIntroductoryRateOnPurchasesTest()
        {
            // TODO unit test for the property 'DurationOfIntroductoryRateOnPurchases'
        }

        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Fact]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }

        /// <summary>
        /// Test the property 'HasCashbackRewards'
        /// </summary>
        [Fact]
        public void HasCashbackRewardsTest()
        {
            // TODO unit test for the property 'HasCashbackRewards'
        }

        /// <summary>
        /// Test the property 'HasOtherRewards'
        /// </summary>
        [Fact]
        public void HasOtherRewardsTest()
        {
            // TODO unit test for the property 'HasOtherRewards'
        }

        /// <summary>
        /// Test the property 'HasTravelRewards'
        /// </summary>
        [Fact]
        public void HasTravelRewardsTest()
        {
            // TODO unit test for the property 'HasTravelRewards'
        }

        /// <summary>
        /// Test the property 'HasZeroIntroductoryAnnualFee'
        /// </summary>
        [Fact]
        public void HasZeroIntroductoryAnnualFeeTest()
        {
            // TODO unit test for the property 'HasZeroIntroductoryAnnualFee'
        }

        /// <summary>
        /// Test the property 'HasZeroPercentIntroductoryRate'
        /// </summary>
        [Fact]
        public void HasZeroPercentIntroductoryRateTest()
        {
            // TODO unit test for the property 'HasZeroPercentIntroductoryRate'
        }

        /// <summary>
        /// Test the property 'HasZeroPercentIntroductoryRateOnBalanceTransfer'
        /// </summary>
        [Fact]
        public void HasZeroPercentIntroductoryRateOnBalanceTransferTest()
        {
            // TODO unit test for the property 'HasZeroPercentIntroductoryRateOnBalanceTransfer'
        }

        /// <summary>
        /// Test the property 'IsAcceptingApplicants'
        /// </summary>
        [Fact]
        public void IsAcceptingApplicantsTest()
        {
            // TODO unit test for the property 'IsAcceptingApplicants'
        }

        /// <summary>
        /// Test the property 'IsActiveCreditCardProduct'
        /// </summary>
        [Fact]
        public void IsActiveCreditCardProductTest()
        {
            // TODO unit test for the property 'IsActiveCreditCardProduct'
        }

        /// <summary>
        /// Test the property 'IsSmallBusinessCard'
        /// </summary>
        [Fact]
        public void IsSmallBusinessCardTest()
        {
            // TODO unit test for the property 'IsSmallBusinessCard'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
