/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Platform.CSharp.Model;
using MX.Platform.CSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Platform.CSharp.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsResponseBody
        //private InsightsResponseBody instance;

        public InsightsResponseBodyTests()
        {
            // TODO uncomment below to create an instance of InsightsResponseBody
            //instance = new InsightsResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsResponseBody
        /// </summary>
        [Fact]
        public void InsightsResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsResponseBody
            //Assert.IsType<InsightsResponseBody>(instance);
        }

        /// <summary>
        /// Test the property 'Insights'
        /// </summary>
        [Fact]
        public void InsightsTest()
        {
            // TODO unit test for the property 'Insights'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
    }
}
