/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Platform.CSharp.Api;
using MX.Platform.CSharp.Model;
using MX.Platform.CSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Platform.CSharp.Test.Model
{
    /// <summary>
    ///  Class for testing StatementResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatementResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StatementResponse
        //private StatementResponse instance;

        public StatementResponseTests()
        {
            // TODO uncomment below to create an instance of StatementResponse
            //instance = new StatementResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatementResponse
        /// </summary>
        [Fact]
        public void StatementResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" StatementResponse
            //Assert.IsType<StatementResponse>(instance);
        }


        /// <summary>
        /// Test the property 'AccountGuid'
        /// </summary>
        [Fact]
        public void AccountGuidTest()
        {
            // TODO unit test for the property 'AccountGuid'
        }
        /// <summary>
        /// Test the property 'ContentHash'
        /// </summary>
        [Fact]
        public void ContentHashTest()
        {
            // TODO unit test for the property 'ContentHash'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Fact]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }
        /// <summary>
        /// Test the property 'MemberGuid'
        /// </summary>
        [Fact]
        public void MemberGuidTest()
        {
            // TODO unit test for the property 'MemberGuid'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Fact]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'UserGuid'
        /// </summary>
        [Fact]
        public void UserGuidTest()
        {
            // TODO unit test for the property 'UserGuid'
        }

    }

}
