/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Platform.CSharp.Model;
using MX.Platform.CSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Platform.CSharp.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionCreateRequest
        //private TransactionCreateRequest instance;

        public TransactionCreateRequestTests()
        {
            // TODO uncomment below to create an instance of TransactionCreateRequest
            //instance = new TransactionCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionCreateRequest
        /// </summary>
        [Fact]
        public void TransactionCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionCreateRequest
            //Assert.IsType<TransactionCreateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'CategoryGuid'
        /// </summary>
        [Fact]
        public void CategoryGuidTest()
        {
            // TODO unit test for the property 'CategoryGuid'
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

        /// <summary>
        /// Test the property 'HasBeenViewed'
        /// </summary>
        [Fact]
        public void HasBeenViewedTest()
        {
            // TODO unit test for the property 'HasBeenViewed'
        }

        /// <summary>
        /// Test the property 'IsHidden'
        /// </summary>
        [Fact]
        public void IsHiddenTest()
        {
            // TODO unit test for the property 'IsHidden'
        }

        /// <summary>
        /// Test the property 'IsInternational'
        /// </summary>
        [Fact]
        public void IsInternationalTest()
        {
            // TODO unit test for the property 'IsInternational'
        }

        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Fact]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'SkipWebhook'
        /// </summary>
        [Fact]
        public void SkipWebhookTest()
        {
            // TODO unit test for the property 'SkipWebhook'
        }
    }
}
