/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Platform.Api;
using MX.Platform.Model;
using MX.Platform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Platform.Test.Model
{
    /// <summary>
    ///  Class for testing HoldingResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HoldingResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HoldingResponseBody
        //private HoldingResponseBody instance;

        public HoldingResponseBodyTests()
        {
            // TODO uncomment below to create an instance of HoldingResponseBody
            //instance = new HoldingResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HoldingResponseBody
        /// </summary>
        [Fact]
        public void HoldingResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" HoldingResponseBody
            //Assert.IsType<HoldingResponseBody>(instance);
        }


        /// <summary>
        /// Test the property 'Holding'
        /// </summary>
        [Fact]
        public void HoldingTest()
        {
            // TODO unit test for the property 'Holding'
        }

    }

}
