/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Platform.Api;
using MX.Platform.Model;
using MX.Platform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Platform.Test.Model
{
    /// <summary>
    ///  Class for testing ManagedTransactionUpdateRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManagedTransactionUpdateRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManagedTransactionUpdateRequestBody
        //private ManagedTransactionUpdateRequestBody instance;

        public ManagedTransactionUpdateRequestBodyTests()
        {
            // TODO uncomment below to create an instance of ManagedTransactionUpdateRequestBody
            //instance = new ManagedTransactionUpdateRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManagedTransactionUpdateRequestBody
        /// </summary>
        [Fact]
        public void ManagedTransactionUpdateRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManagedTransactionUpdateRequestBody
            //Assert.IsType<ManagedTransactionUpdateRequestBody>(instance);
        }


        /// <summary>
        /// Test the property 'Transaction'
        /// </summary>
        [Fact]
        public void TransactionTest()
        {
            // TODO unit test for the property 'Transaction'
        }

    }

}
