/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Platform.Api;
using MX.Platform.Model;
using MX.Platform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Platform.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionResponse
        //private TransactionResponse instance;

        public TransactionResponseTests()
        {
            // TODO uncomment below to create an instance of TransactionResponse
            //instance = new TransactionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionResponse
        /// </summary>
        [Fact]
        public void TransactionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionResponse
            //Assert.IsType<TransactionResponse>(instance);
        }


        /// <summary>
        /// Test the property 'AccountGuid'
        /// </summary>
        [Fact]
        public void AccountGuidTest()
        {
            // TODO unit test for the property 'AccountGuid'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'CategoryGuid'
        /// </summary>
        [Fact]
        public void CategoryGuidTest()
        {
            // TODO unit test for the property 'CategoryGuid'
        }
        /// <summary>
        /// Test the property 'CheckNumberString'
        /// </summary>
        [Fact]
        public void CheckNumberStringTest()
        {
            // TODO unit test for the property 'CheckNumberString'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ExtendedTransactionType'
        /// </summary>
        [Fact]
        public void ExtendedTransactionTypeTest()
        {
            // TODO unit test for the property 'ExtendedTransactionType'
        }
        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Fact]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsBillPay'
        /// </summary>
        [Fact]
        public void IsBillPayTest()
        {
            // TODO unit test for the property 'IsBillPay'
        }
        /// <summary>
        /// Test the property 'IsDirectDeposit'
        /// </summary>
        [Fact]
        public void IsDirectDepositTest()
        {
            // TODO unit test for the property 'IsDirectDeposit'
        }
        /// <summary>
        /// Test the property 'IsExpense'
        /// </summary>
        [Fact]
        public void IsExpenseTest()
        {
            // TODO unit test for the property 'IsExpense'
        }
        /// <summary>
        /// Test the property 'IsFee'
        /// </summary>
        [Fact]
        public void IsFeeTest()
        {
            // TODO unit test for the property 'IsFee'
        }
        /// <summary>
        /// Test the property 'IsIncome'
        /// </summary>
        [Fact]
        public void IsIncomeTest()
        {
            // TODO unit test for the property 'IsIncome'
        }
        /// <summary>
        /// Test the property 'IsInternational'
        /// </summary>
        [Fact]
        public void IsInternationalTest()
        {
            // TODO unit test for the property 'IsInternational'
        }
        /// <summary>
        /// Test the property 'IsOverdraftFee'
        /// </summary>
        [Fact]
        public void IsOverdraftFeeTest()
        {
            // TODO unit test for the property 'IsOverdraftFee'
        }
        /// <summary>
        /// Test the property 'IsPayrollAdvance'
        /// </summary>
        [Fact]
        public void IsPayrollAdvanceTest()
        {
            // TODO unit test for the property 'IsPayrollAdvance'
        }
        /// <summary>
        /// Test the property 'IsRecurring'
        /// </summary>
        [Fact]
        public void IsRecurringTest()
        {
            // TODO unit test for the property 'IsRecurring'
        }
        /// <summary>
        /// Test the property 'IsSubscription'
        /// </summary>
        [Fact]
        public void IsSubscriptionTest()
        {
            // TODO unit test for the property 'IsSubscription'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'LocalizedDescription'
        /// </summary>
        [Fact]
        public void LocalizedDescriptionTest()
        {
            // TODO unit test for the property 'LocalizedDescription'
        }
        /// <summary>
        /// Test the property 'LocalizedMemo'
        /// </summary>
        [Fact]
        public void LocalizedMemoTest()
        {
            // TODO unit test for the property 'LocalizedMemo'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'MemberGuid'
        /// </summary>
        [Fact]
        public void MemberGuidTest()
        {
            // TODO unit test for the property 'MemberGuid'
        }
        /// <summary>
        /// Test the property 'MemberIsManagedByUser'
        /// </summary>
        [Fact]
        public void MemberIsManagedByUserTest()
        {
            // TODO unit test for the property 'MemberIsManagedByUser'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Fact]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'MerchantCategoryCode'
        /// </summary>
        [Fact]
        public void MerchantCategoryCodeTest()
        {
            // TODO unit test for the property 'MerchantCategoryCode'
        }
        /// <summary>
        /// Test the property 'MerchantGuid'
        /// </summary>
        [Fact]
        public void MerchantGuidTest()
        {
            // TODO unit test for the property 'MerchantGuid'
        }
        /// <summary>
        /// Test the property 'MerchantLocationGuid'
        /// </summary>
        [Fact]
        public void MerchantLocationGuidTest()
        {
            // TODO unit test for the property 'MerchantLocationGuid'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'OriginalDescription'
        /// </summary>
        [Fact]
        public void OriginalDescriptionTest()
        {
            // TODO unit test for the property 'OriginalDescription'
        }
        /// <summary>
        /// Test the property 'PostedAt'
        /// </summary>
        [Fact]
        public void PostedAtTest()
        {
            // TODO unit test for the property 'PostedAt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TopLevelCategory'
        /// </summary>
        [Fact]
        public void TopLevelCategoryTest()
        {
            // TODO unit test for the property 'TopLevelCategory'
        }
        /// <summary>
        /// Test the property 'TransactedAt'
        /// </summary>
        [Fact]
        public void TransactedAtTest()
        {
            // TODO unit test for the property 'TransactedAt'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'UserGuid'
        /// </summary>
        [Fact]
        public void UserGuidTest()
        {
            // TODO unit test for the property 'UserGuid'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

    }

}
