/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MX.Platform.Api;
using MX.Platform.Model;
using MX.Platform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MX.Platform.Test.Model
{
    /// <summary>
    ///  Class for testing UsersResponseBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UsersResponseBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UsersResponseBody
        //private UsersResponseBody instance;

        public UsersResponseBodyTests()
        {
            // TODO uncomment below to create an instance of UsersResponseBody
            //instance = new UsersResponseBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsersResponseBody
        /// </summary>
        [Fact]
        public void UsersResponseBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UsersResponseBody
            //Assert.IsType<UsersResponseBody>(instance);
        }


        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Fact]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }

    }

}
