/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MX.Platform.CSharp.Client.OpenAPIDateConverter;

namespace MX.Platform.CSharp.Model
{
    /// <summary>
    /// MemberCreateRequest
    /// </summary>
    [DataContract(Name = "MemberCreateRequest")]
    public partial class MemberCreateRequest : IEquatable<MemberCreateRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines UseCases
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum UseCasesEnum
        {
            /// <summary>
            /// Enum MONEYMOVEMENT for value: MONEY_MOVEMENT
            /// </summary>
            [EnumMember(Value = "MONEY_MOVEMENT")]
            MONEYMOVEMENT = 1,

            /// <summary>
            /// Enum PFM for value: PFM
            /// </summary>
            [EnumMember(Value = "PFM")]
            PFM = 2
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MemberCreateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MemberCreateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MemberCreateRequest" /> class.
        /// </summary>
        /// <param name="backgroundAggregationIsDisabled">backgroundAggregationIsDisabled.</param>
        /// <param name="credentials">credentials (required).</param>
        /// <param name="id">id.</param>
        /// <param name="institutionCode">institutionCode (required).</param>
        /// <param name="isOauth">isOauth.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="skipAggregation">skipAggregation.</param>
        /// <param name="useCases">The use case associated with the member. Valid values are &#x60;PFM&#x60; and/or &#x60;MONEY_MOVEMENT&#x60;. Only set this if you&#39;ve met with MX and have opted in to using this field..</param>
        public MemberCreateRequest(bool backgroundAggregationIsDisabled = default(bool), List<CredentialRequest> credentials = default(List<CredentialRequest>), string id = default(string), string institutionCode = default(string), bool isOauth = default(bool), string metadata = default(string), bool skipAggregation = default(bool), List<UseCasesEnum> useCases = default(List<UseCasesEnum>))
        {
            // to ensure "credentials" is required (not null)
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials is a required property for MemberCreateRequest and cannot be null");
            }
            this.Credentials = credentials;
            // to ensure "institutionCode" is required (not null)
            if (institutionCode == null)
            {
                throw new ArgumentNullException("institutionCode is a required property for MemberCreateRequest and cannot be null");
            }
            this.InstitutionCode = institutionCode;
            this.BackgroundAggregationIsDisabled = backgroundAggregationIsDisabled;
            this.Id = id;
            this.IsOauth = isOauth;
            this.Metadata = metadata;
            this.SkipAggregation = skipAggregation;
            this.UseCases = useCases;
        }

        /// <summary>
        /// Gets or Sets BackgroundAggregationIsDisabled
        /// </summary>
        /// <example>false</example>
        [DataMember(Name = "background_aggregation_is_disabled", EmitDefaultValue = true)]
        public bool BackgroundAggregationIsDisabled { get; set; }

        /// <summary>
        /// Gets or Sets Credentials
        /// </summary>
        [DataMember(Name = "credentials", IsRequired = true, EmitDefaultValue = true)]
        public List<CredentialRequest> Credentials { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /// <example>unique_id</example>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets InstitutionCode
        /// </summary>
        /// <example>mxbank</example>
        [DataMember(Name = "institution_code", IsRequired = true, EmitDefaultValue = true)]
        public string InstitutionCode { get; set; }

        /// <summary>
        /// Gets or Sets IsOauth
        /// </summary>
        /// <example>false</example>
        [DataMember(Name = "is_oauth", EmitDefaultValue = true)]
        public bool IsOauth { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        /// <example>\&quot;credentials_last_refreshed_at\&quot;: \&quot;2015-10-15\</example>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public string Metadata { get; set; }

        /// <summary>
        /// Gets or Sets SkipAggregation
        /// </summary>
        /// <example>false</example>
        [DataMember(Name = "skip_aggregation", EmitDefaultValue = true)]
        public bool SkipAggregation { get; set; }

        /// <summary>
        /// The use case associated with the member. Valid values are &#x60;PFM&#x60; and/or &#x60;MONEY_MOVEMENT&#x60;. Only set this if you&#39;ve met with MX and have opted in to using this field.
        /// </summary>
        /// <value>The use case associated with the member. Valid values are &#x60;PFM&#x60; and/or &#x60;MONEY_MOVEMENT&#x60;. Only set this if you&#39;ve met with MX and have opted in to using this field.</value>
        /// <example>[&quot;PFM&quot;]</example>
        [DataMember(Name = "use_cases", EmitDefaultValue = false)]
        public List<MemberCreateRequest.UseCasesEnum> UseCases { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MemberCreateRequest {\n");
            sb.Append("  BackgroundAggregationIsDisabled: ").Append(BackgroundAggregationIsDisabled).Append("\n");
            sb.Append("  Credentials: ").Append(Credentials).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InstitutionCode: ").Append(InstitutionCode).Append("\n");
            sb.Append("  IsOauth: ").Append(IsOauth).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  SkipAggregation: ").Append(SkipAggregation).Append("\n");
            sb.Append("  UseCases: ").Append(UseCases).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MemberCreateRequest);
        }

        /// <summary>
        /// Returns true if MemberCreateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of MemberCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MemberCreateRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.BackgroundAggregationIsDisabled == input.BackgroundAggregationIsDisabled ||
                    this.BackgroundAggregationIsDisabled.Equals(input.BackgroundAggregationIsDisabled)
                ) && 
                (
                    this.Credentials == input.Credentials ||
                    this.Credentials != null &&
                    input.Credentials != null &&
                    this.Credentials.SequenceEqual(input.Credentials)
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.InstitutionCode == input.InstitutionCode ||
                    (this.InstitutionCode != null &&
                    this.InstitutionCode.Equals(input.InstitutionCode))
                ) && 
                (
                    this.IsOauth == input.IsOauth ||
                    this.IsOauth.Equals(input.IsOauth)
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    (this.Metadata != null &&
                    this.Metadata.Equals(input.Metadata))
                ) && 
                (
                    this.SkipAggregation == input.SkipAggregation ||
                    this.SkipAggregation.Equals(input.SkipAggregation)
                ) && 
                (
                    this.UseCases == input.UseCases ||
                    this.UseCases != null &&
                    input.UseCases != null &&
                    this.UseCases.SequenceEqual(input.UseCases)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.BackgroundAggregationIsDisabled.GetHashCode();
                if (this.Credentials != null)
                {
                    hashCode = (hashCode * 59) + this.Credentials.GetHashCode();
                }
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.InstitutionCode != null)
                {
                    hashCode = (hashCode * 59) + this.InstitutionCode.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsOauth.GetHashCode();
                if (this.Metadata != null)
                {
                    hashCode = (hashCode * 59) + this.Metadata.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.SkipAggregation.GetHashCode();
                if (this.UseCases != null)
                {
                    hashCode = (hashCode * 59) + this.UseCases.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
