/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MX.Platform.CSharp.Client.OpenAPIDateConverter;

namespace MX.Platform.CSharp.Model
{
    /// <summary>
    /// ProcessorOwner
    /// </summary>
    [DataContract(Name = "ProcessorOwner")]
    public partial class ProcessorOwner : IEquatable<ProcessorOwner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessorOwner" /> class.
        /// </summary>
        /// <param name="guid">guid.</param>
        /// <param name="ownerName">ownerName.</param>
        /// <param name="address">address.</param>
        /// <param name="city">city.</param>
        /// <param name="state">state.</param>
        /// <param name="postalCode">postalCode.</param>
        /// <param name="country">country.</param>
        /// <param name="email">email.</param>
        /// <param name="phone">phone.</param>
        public ProcessorOwner(Object guid = default(Object), Object ownerName = default(Object), Object address = default(Object), Object city = default(Object), Object state = default(Object), Object postalCode = default(Object), Object country = default(Object), Object email = default(Object), Object phone = default(Object))
        {
            this.Guid = guid;
            this.OwnerName = ownerName;
            this.Address = address;
            this.City = city;
            this.State = state;
            this.PostalCode = postalCode;
            this.Country = country;
            this.Email = email;
            this.Phone = phone;
        }

        /// <summary>
        /// Gets or Sets Guid
        /// </summary>
        /// <example>ACO-a06b74ec-6a58-4c0b-b437-8de5e03194ac</example>
        [DataMember(Name = "guid", EmitDefaultValue = true)]
        public Object Guid { get; set; }

        /// <summary>
        /// Gets or Sets OwnerName
        /// </summary>
        /// <example>Janita Pollich</example>
        [DataMember(Name = "owner_name", EmitDefaultValue = true)]
        public Object OwnerName { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        /// <example>3541 Adrian Street</example>
        [DataMember(Name = "address", EmitDefaultValue = true)]
        public Object Address { get; set; }

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        /// <example>North Kishaberg</example>
        [DataMember(Name = "city", EmitDefaultValue = true)]
        public Object City { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        /// <example>Maine</example>
        [DataMember(Name = "state", EmitDefaultValue = true)]
        public Object State { get; set; }

        /// <summary>
        /// Gets or Sets PostalCode
        /// </summary>
        /// <example>45054-7764</example>
        [DataMember(Name = "postal_code", EmitDefaultValue = true)]
        public Object PostalCode { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = true)]
        public Object Country { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        /// <example>janita.pollich823@beerpowlowski.ca</example>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public Object Email { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        /// <example>676-932-5861</example>
        [DataMember(Name = "phone", EmitDefaultValue = true)]
        public Object Phone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProcessorOwner {\n");
            sb.Append("  Guid: ").Append(Guid).Append("\n");
            sb.Append("  OwnerName: ").Append(OwnerName).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProcessorOwner);
        }

        /// <summary>
        /// Returns true if ProcessorOwner instances are equal
        /// </summary>
        /// <param name="input">Instance of ProcessorOwner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProcessorOwner input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Guid == input.Guid ||
                    (this.Guid != null &&
                    this.Guid.Equals(input.Guid))
                ) && 
                (
                    this.OwnerName == input.OwnerName ||
                    (this.OwnerName != null &&
                    this.OwnerName.Equals(input.OwnerName))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.City == input.City ||
                    (this.City != null &&
                    this.City.Equals(input.City))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.PostalCode == input.PostalCode ||
                    (this.PostalCode != null &&
                    this.PostalCode.Equals(input.PostalCode))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Phone == input.Phone ||
                    (this.Phone != null &&
                    this.Phone.Equals(input.Phone))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Guid != null)
                {
                    hashCode = (hashCode * 59) + this.Guid.GetHashCode();
                }
                if (this.OwnerName != null)
                {
                    hashCode = (hashCode * 59) + this.OwnerName.GetHashCode();
                }
                if (this.Address != null)
                {
                    hashCode = (hashCode * 59) + this.Address.GetHashCode();
                }
                if (this.City != null)
                {
                    hashCode = (hashCode * 59) + this.City.GetHashCode();
                }
                if (this.State != null)
                {
                    hashCode = (hashCode * 59) + this.State.GetHashCode();
                }
                if (this.PostalCode != null)
                {
                    hashCode = (hashCode * 59) + this.PostalCode.GetHashCode();
                }
                if (this.Country != null)
                {
                    hashCode = (hashCode * 59) + this.Country.GetHashCode();
                }
                if (this.Email != null)
                {
                    hashCode = (hashCode * 59) + this.Email.GetHashCode();
                }
                if (this.Phone != null)
                {
                    hashCode = (hashCode * 59) + this.Phone.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
