/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MX.Platform.CSharp.Client.OpenAPIDateConverter;

namespace MX.Platform.CSharp.Model
{
    /// <summary>
    /// ProcessorOwnerBodyAccountOwnersInner
    /// </summary>
    [DataContract(Name = "ProcessorOwnerBody_account_owners_inner")]
    public partial class ProcessorOwnerBodyAccountOwnersInner : IEquatable<ProcessorOwnerBodyAccountOwnersInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessorOwnerBodyAccountOwnersInner" /> class.
        /// </summary>
        /// <param name="accountGuid">accountGuid.</param>
        /// <param name="memberGuid">memberGuid.</param>
        /// <param name="userGuid">userGuid.</param>
        /// <param name="guid">guid.</param>
        /// <param name="ownerName">ownerName.</param>
        /// <param name="address">address.</param>
        /// <param name="city">city.</param>
        /// <param name="state">state.</param>
        /// <param name="postalCode">postalCode.</param>
        /// <param name="country">country.</param>
        /// <param name="email">email.</param>
        /// <param name="phone">phone.</param>
        public ProcessorOwnerBodyAccountOwnersInner(string accountGuid = default(string), string memberGuid = default(string), string userGuid = default(string), Object guid = default(Object), Object ownerName = default(Object), Object address = default(Object), Object city = default(Object), Object state = default(Object), Object postalCode = default(Object), Object country = default(Object), Object email = default(Object), Object phone = default(Object))
        {
            this.AccountGuid = accountGuid;
            this.MemberGuid = memberGuid;
            this.UserGuid = userGuid;
            this.Guid = guid;
            this.OwnerName = ownerName;
            this.Address = address;
            this.City = city;
            this.State = state;
            this.PostalCode = postalCode;
            this.Country = country;
            this.Email = email;
            this.Phone = phone;
        }

        /// <summary>
        /// Gets or Sets AccountGuid
        /// </summary>
        /// <example>ACT-283132a4-1401-486a-909e-1605f1623d11</example>
        [DataMember(Name = "account_guid", EmitDefaultValue = false)]
        public string AccountGuid { get; set; }

        /// <summary>
        /// Gets or Sets MemberGuid
        /// </summary>
        /// <example>MBR-54feffb9-8474-47bd-8442-de003910113a</example>
        [DataMember(Name = "member_guid", EmitDefaultValue = false)]
        public string MemberGuid { get; set; }

        /// <summary>
        /// Gets or Sets UserGuid
        /// </summary>
        /// <example>USR-101ad774-288b-44ed-ad16-da87d522ea20</example>
        [DataMember(Name = "user_guid", EmitDefaultValue = false)]
        public string UserGuid { get; set; }

        /// <summary>
        /// Gets or Sets Guid
        /// </summary>
        /// <example>ACO-a06b74ec-6a58-4c0b-b437-8de5e03194ac</example>
        [DataMember(Name = "guid", EmitDefaultValue = true)]
        public Object Guid { get; set; }

        /// <summary>
        /// Gets or Sets OwnerName
        /// </summary>
        /// <example>Janita Pollich</example>
        [DataMember(Name = "owner_name", EmitDefaultValue = true)]
        public Object OwnerName { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        /// <example>3541 Adrian Street</example>
        [DataMember(Name = "address", EmitDefaultValue = true)]
        public Object Address { get; set; }

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        /// <example>North Kishaberg</example>
        [DataMember(Name = "city", EmitDefaultValue = true)]
        public Object City { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        /// <example>Maine</example>
        [DataMember(Name = "state", EmitDefaultValue = true)]
        public Object State { get; set; }

        /// <summary>
        /// Gets or Sets PostalCode
        /// </summary>
        /// <example>45054-7764</example>
        [DataMember(Name = "postal_code", EmitDefaultValue = true)]
        public Object PostalCode { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = true)]
        public Object Country { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        /// <example>janita.pollich823@beerpowlowski.ca</example>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public Object Email { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        /// <example>676-932-5861</example>
        [DataMember(Name = "phone", EmitDefaultValue = true)]
        public Object Phone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProcessorOwnerBodyAccountOwnersInner {\n");
            sb.Append("  AccountGuid: ").Append(AccountGuid).Append("\n");
            sb.Append("  MemberGuid: ").Append(MemberGuid).Append("\n");
            sb.Append("  UserGuid: ").Append(UserGuid).Append("\n");
            sb.Append("  Guid: ").Append(Guid).Append("\n");
            sb.Append("  OwnerName: ").Append(OwnerName).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProcessorOwnerBodyAccountOwnersInner);
        }

        /// <summary>
        /// Returns true if ProcessorOwnerBodyAccountOwnersInner instances are equal
        /// </summary>
        /// <param name="input">Instance of ProcessorOwnerBodyAccountOwnersInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProcessorOwnerBodyAccountOwnersInner input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AccountGuid == input.AccountGuid ||
                    (this.AccountGuid != null &&
                    this.AccountGuid.Equals(input.AccountGuid))
                ) && 
                (
                    this.MemberGuid == input.MemberGuid ||
                    (this.MemberGuid != null &&
                    this.MemberGuid.Equals(input.MemberGuid))
                ) && 
                (
                    this.UserGuid == input.UserGuid ||
                    (this.UserGuid != null &&
                    this.UserGuid.Equals(input.UserGuid))
                ) && 
                (
                    this.Guid == input.Guid ||
                    (this.Guid != null &&
                    this.Guid.Equals(input.Guid))
                ) && 
                (
                    this.OwnerName == input.OwnerName ||
                    (this.OwnerName != null &&
                    this.OwnerName.Equals(input.OwnerName))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.City == input.City ||
                    (this.City != null &&
                    this.City.Equals(input.City))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.PostalCode == input.PostalCode ||
                    (this.PostalCode != null &&
                    this.PostalCode.Equals(input.PostalCode))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Phone == input.Phone ||
                    (this.Phone != null &&
                    this.Phone.Equals(input.Phone))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccountGuid != null)
                {
                    hashCode = (hashCode * 59) + this.AccountGuid.GetHashCode();
                }
                if (this.MemberGuid != null)
                {
                    hashCode = (hashCode * 59) + this.MemberGuid.GetHashCode();
                }
                if (this.UserGuid != null)
                {
                    hashCode = (hashCode * 59) + this.UserGuid.GetHashCode();
                }
                if (this.Guid != null)
                {
                    hashCode = (hashCode * 59) + this.Guid.GetHashCode();
                }
                if (this.OwnerName != null)
                {
                    hashCode = (hashCode * 59) + this.OwnerName.GetHashCode();
                }
                if (this.Address != null)
                {
                    hashCode = (hashCode * 59) + this.Address.GetHashCode();
                }
                if (this.City != null)
                {
                    hashCode = (hashCode * 59) + this.City.GetHashCode();
                }
                if (this.State != null)
                {
                    hashCode = (hashCode * 59) + this.State.GetHashCode();
                }
                if (this.PostalCode != null)
                {
                    hashCode = (hashCode * 59) + this.PostalCode.GetHashCode();
                }
                if (this.Country != null)
                {
                    hashCode = (hashCode * 59) + this.Country.GetHashCode();
                }
                if (this.Email != null)
                {
                    hashCode = (hashCode * 59) + this.Email.GetHashCode();
                }
                if (this.Phone != null)
                {
                    hashCode = (hashCode * 59) + this.Phone.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
