/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MX.Platform.CSharp.Client.OpenAPIDateConverter;

namespace MX.Platform.CSharp.Model
{
    /// <summary>
    /// RepositionRequest
    /// </summary>
    [DataContract(Name = "RepositionRequest")]
    public partial class RepositionRequest : IEquatable<RepositionRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RepositionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RepositionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RepositionRequest" /> class.
        /// </summary>
        /// <param name="guid">The unique identifier for the goal. Defined by MX. (required).</param>
        /// <param name="position">The priority of the goal in relation to multiple goals. (required).</param>
        public RepositionRequest(string guid = default(string), int position = default(int))
        {
            // to ensure "guid" is required (not null)
            if (guid == null)
            {
                throw new ArgumentNullException("guid is a required property for RepositionRequest and cannot be null");
            }
            this.Guid = guid;
            this.Position = position;
        }

        /// <summary>
        /// The unique identifier for the goal. Defined by MX.
        /// </summary>
        /// <value>The unique identifier for the goal. Defined by MX.</value>
        /// <example>GOL-97665947-235c-b213-ca25-8cf0174774f5</example>
        [DataMember(Name = "guid", IsRequired = true, EmitDefaultValue = true)]
        public string Guid { get; set; }

        /// <summary>
        /// The priority of the goal in relation to multiple goals.
        /// </summary>
        /// <value>The priority of the goal in relation to multiple goals.</value>
        /// <example>1</example>
        [DataMember(Name = "position", IsRequired = true, EmitDefaultValue = true)]
        public int Position { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RepositionRequest {\n");
            sb.Append("  Guid: ").Append(Guid).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RepositionRequest);
        }

        /// <summary>
        /// Returns true if RepositionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of RepositionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RepositionRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Guid == input.Guid ||
                    (this.Guid != null &&
                    this.Guid.Equals(input.Guid))
                ) && 
                (
                    this.Position == input.Position ||
                    this.Position.Equals(input.Position)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Guid != null)
                {
                    hashCode = (hashCode * 59) + this.Guid.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Position.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
