/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using MX.Platform.CSharp.Client;
using MX.Platform.CSharp.Model;

namespace MX.Platform.CSharp.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITransactionRulesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to create a new transaction rule. The newly-created &#x60;transaction_rule&#x60; object will be returned if successful.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleCreateRequestBody">TransactionRule object to be created with optional parameters (description) and required parameters (category_guid and match_description)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TransactionRuleResponseBody</returns>
        TransactionRuleResponseBody CreateTransactionRule(string userGuid, TransactionRuleCreateRequestBody transactionRuleCreateRequestBody, int operationIndex = 0);

        /// <summary>
        /// Create transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to create a new transaction rule. The newly-created &#x60;transaction_rule&#x60; object will be returned if successful.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleCreateRequestBody">TransactionRule object to be created with optional parameters (description) and required parameters (category_guid and match_description)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TransactionRuleResponseBody</returns>
        ApiResponse<TransactionRuleResponseBody> CreateTransactionRuleWithHttpInfo(string userGuid, TransactionRuleCreateRequestBody transactionRuleCreateRequestBody, int operationIndex = 0);
        /// <summary>
        /// List transaction rules
        /// </summary>
        /// <remarks>
        /// Use this endpoint to read the attributes of all existing transaction rules belonging to the user.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="page">Results are paginated. Specify current page. (optional)</param>
        /// <param name="recordsPerPage">This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TransactionRulesResponseBody</returns>
        TransactionRulesResponseBody ListTransactionRules(string userGuid, int? page = default(int?), int? recordsPerPage = default(int?), int operationIndex = 0);

        /// <summary>
        /// List transaction rules
        /// </summary>
        /// <remarks>
        /// Use this endpoint to read the attributes of all existing transaction rules belonging to the user.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="page">Results are paginated. Specify current page. (optional)</param>
        /// <param name="recordsPerPage">This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TransactionRulesResponseBody</returns>
        ApiResponse<TransactionRulesResponseBody> ListTransactionRulesWithHttpInfo(string userGuid, int? page = default(int?), int? recordsPerPage = default(int?), int operationIndex = 0);
        /// <summary>
        /// Read transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to read the attributes of an existing transaction rule based on the rule’s unique GUID.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TransactionRuleResponseBody</returns>
        TransactionRuleResponseBody ReadTransactionRule(string transactionRuleGuid, string userGuid, int operationIndex = 0);

        /// <summary>
        /// Read transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to read the attributes of an existing transaction rule based on the rule’s unique GUID.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TransactionRuleResponseBody</returns>
        ApiResponse<TransactionRuleResponseBody> ReadTransactionRuleWithHttpInfo(string transactionRuleGuid, string userGuid, int operationIndex = 0);
        /// <summary>
        /// Update transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to update the attributes of a specific transaction rule based on its unique GUID. The API will respond with the updated transaction_rule object. Any attributes not provided will be left unchanged.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleUpdateRequestBody">TransactionRule object to be updated</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TransactionRuleResponseBody</returns>
        TransactionRuleResponseBody UpdateTransactionRule(string transactionRuleGuid, string userGuid, TransactionRuleUpdateRequestBody transactionRuleUpdateRequestBody, int operationIndex = 0);

        /// <summary>
        /// Update transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to update the attributes of a specific transaction rule based on its unique GUID. The API will respond with the updated transaction_rule object. Any attributes not provided will be left unchanged.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleUpdateRequestBody">TransactionRule object to be updated</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TransactionRuleResponseBody</returns>
        ApiResponse<TransactionRuleResponseBody> UpdateTransactionRuleWithHttpInfo(string transactionRuleGuid, string userGuid, TransactionRuleUpdateRequestBody transactionRuleUpdateRequestBody, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITransactionRulesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to create a new transaction rule. The newly-created &#x60;transaction_rule&#x60; object will be returned if successful.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleCreateRequestBody">TransactionRule object to be created with optional parameters (description) and required parameters (category_guid and match_description)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionRuleResponseBody</returns>
        System.Threading.Tasks.Task<TransactionRuleResponseBody> CreateTransactionRuleAsync(string userGuid, TransactionRuleCreateRequestBody transactionRuleCreateRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to create a new transaction rule. The newly-created &#x60;transaction_rule&#x60; object will be returned if successful.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleCreateRequestBody">TransactionRule object to be created with optional parameters (description) and required parameters (category_guid and match_description)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionRuleResponseBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<TransactionRuleResponseBody>> CreateTransactionRuleWithHttpInfoAsync(string userGuid, TransactionRuleCreateRequestBody transactionRuleCreateRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List transaction rules
        /// </summary>
        /// <remarks>
        /// Use this endpoint to read the attributes of all existing transaction rules belonging to the user.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="page">Results are paginated. Specify current page. (optional)</param>
        /// <param name="recordsPerPage">This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionRulesResponseBody</returns>
        System.Threading.Tasks.Task<TransactionRulesResponseBody> ListTransactionRulesAsync(string userGuid, int? page = default(int?), int? recordsPerPage = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List transaction rules
        /// </summary>
        /// <remarks>
        /// Use this endpoint to read the attributes of all existing transaction rules belonging to the user.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="page">Results are paginated. Specify current page. (optional)</param>
        /// <param name="recordsPerPage">This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionRulesResponseBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<TransactionRulesResponseBody>> ListTransactionRulesWithHttpInfoAsync(string userGuid, int? page = default(int?), int? recordsPerPage = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Read transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to read the attributes of an existing transaction rule based on the rule’s unique GUID.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionRuleResponseBody</returns>
        System.Threading.Tasks.Task<TransactionRuleResponseBody> ReadTransactionRuleAsync(string transactionRuleGuid, string userGuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Read transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to read the attributes of an existing transaction rule based on the rule’s unique GUID.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionRuleResponseBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<TransactionRuleResponseBody>> ReadTransactionRuleWithHttpInfoAsync(string transactionRuleGuid, string userGuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to update the attributes of a specific transaction rule based on its unique GUID. The API will respond with the updated transaction_rule object. Any attributes not provided will be left unchanged.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleUpdateRequestBody">TransactionRule object to be updated</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionRuleResponseBody</returns>
        System.Threading.Tasks.Task<TransactionRuleResponseBody> UpdateTransactionRuleAsync(string transactionRuleGuid, string userGuid, TransactionRuleUpdateRequestBody transactionRuleUpdateRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update transaction rule
        /// </summary>
        /// <remarks>
        /// Use this endpoint to update the attributes of a specific transaction rule based on its unique GUID. The API will respond with the updated transaction_rule object. Any attributes not provided will be left unchanged.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleUpdateRequestBody">TransactionRule object to be updated</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionRuleResponseBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<TransactionRuleResponseBody>> UpdateTransactionRuleWithHttpInfoAsync(string transactionRuleGuid, string userGuid, TransactionRuleUpdateRequestBody transactionRuleUpdateRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITransactionRulesApi : ITransactionRulesApiSync, ITransactionRulesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TransactionRulesApi : ITransactionRulesApi
    {
        private MX.Platform.CSharp.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionRulesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TransactionRulesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionRulesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TransactionRulesApi(string basePath)
        {
            this.Configuration = MX.Platform.CSharp.Client.Configuration.MergeConfigurations(
                MX.Platform.CSharp.Client.GlobalConfiguration.Instance,
                new MX.Platform.CSharp.Client.Configuration { BasePath = basePath }
            );
            this.Client = new MX.Platform.CSharp.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MX.Platform.CSharp.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = MX.Platform.CSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionRulesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TransactionRulesApi(MX.Platform.CSharp.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MX.Platform.CSharp.Client.Configuration.MergeConfigurations(
                MX.Platform.CSharp.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new MX.Platform.CSharp.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MX.Platform.CSharp.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = MX.Platform.CSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionRulesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TransactionRulesApi(MX.Platform.CSharp.Client.ISynchronousClient client, MX.Platform.CSharp.Client.IAsynchronousClient asyncClient, MX.Platform.CSharp.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MX.Platform.CSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public MX.Platform.CSharp.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public MX.Platform.CSharp.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MX.Platform.CSharp.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MX.Platform.CSharp.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create transaction rule Use this endpoint to create a new transaction rule. The newly-created &#x60;transaction_rule&#x60; object will be returned if successful.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleCreateRequestBody">TransactionRule object to be created with optional parameters (description) and required parameters (category_guid and match_description)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TransactionRuleResponseBody</returns>
        public TransactionRuleResponseBody CreateTransactionRule(string userGuid, TransactionRuleCreateRequestBody transactionRuleCreateRequestBody, int operationIndex = 0)
        {
            MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody> localVarResponse = CreateTransactionRuleWithHttpInfo(userGuid, transactionRuleCreateRequestBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create transaction rule Use this endpoint to create a new transaction rule. The newly-created &#x60;transaction_rule&#x60; object will be returned if successful.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleCreateRequestBody">TransactionRule object to be created with optional parameters (description) and required parameters (category_guid and match_description)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TransactionRuleResponseBody</returns>
        public MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody> CreateTransactionRuleWithHttpInfo(string userGuid, TransactionRuleCreateRequestBody transactionRuleCreateRequestBody, int operationIndex = 0)
        {
            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling TransactionRulesApi->CreateTransactionRule");
            }

            // verify the required parameter 'transactionRuleCreateRequestBody' is set
            if (transactionRuleCreateRequestBody == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'transactionRuleCreateRequestBody' when calling TransactionRulesApi->CreateTransactionRule");
            }

            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            localVarRequestOptions.Data = transactionRuleCreateRequestBody;

            localVarRequestOptions.Operation = "TransactionRulesApi.CreateTransactionRule";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TransactionRuleResponseBody>("/users/{user_guid}/transaction_rules", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTransactionRule", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create transaction rule Use this endpoint to create a new transaction rule. The newly-created &#x60;transaction_rule&#x60; object will be returned if successful.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleCreateRequestBody">TransactionRule object to be created with optional parameters (description) and required parameters (category_guid and match_description)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionRuleResponseBody</returns>
        public async System.Threading.Tasks.Task<TransactionRuleResponseBody> CreateTransactionRuleAsync(string userGuid, TransactionRuleCreateRequestBody transactionRuleCreateRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody> localVarResponse = await CreateTransactionRuleWithHttpInfoAsync(userGuid, transactionRuleCreateRequestBody, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create transaction rule Use this endpoint to create a new transaction rule. The newly-created &#x60;transaction_rule&#x60; object will be returned if successful.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleCreateRequestBody">TransactionRule object to be created with optional parameters (description) and required parameters (category_guid and match_description)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionRuleResponseBody)</returns>
        public async System.Threading.Tasks.Task<MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody>> CreateTransactionRuleWithHttpInfoAsync(string userGuid, TransactionRuleCreateRequestBody transactionRuleCreateRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling TransactionRulesApi->CreateTransactionRule");
            }

            // verify the required parameter 'transactionRuleCreateRequestBody' is set
            if (transactionRuleCreateRequestBody == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'transactionRuleCreateRequestBody' when calling TransactionRulesApi->CreateTransactionRule");
            }


            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            localVarRequestOptions.Data = transactionRuleCreateRequestBody;

            localVarRequestOptions.Operation = "TransactionRulesApi.CreateTransactionRule";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<TransactionRuleResponseBody>("/users/{user_guid}/transaction_rules", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTransactionRule", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List transaction rules Use this endpoint to read the attributes of all existing transaction rules belonging to the user.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="page">Results are paginated. Specify current page. (optional)</param>
        /// <param name="recordsPerPage">This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TransactionRulesResponseBody</returns>
        public TransactionRulesResponseBody ListTransactionRules(string userGuid, int? page = default(int?), int? recordsPerPage = default(int?), int operationIndex = 0)
        {
            MX.Platform.CSharp.Client.ApiResponse<TransactionRulesResponseBody> localVarResponse = ListTransactionRulesWithHttpInfo(userGuid, page, recordsPerPage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List transaction rules Use this endpoint to read the attributes of all existing transaction rules belonging to the user.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="page">Results are paginated. Specify current page. (optional)</param>
        /// <param name="recordsPerPage">This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TransactionRulesResponseBody</returns>
        public MX.Platform.CSharp.Client.ApiResponse<TransactionRulesResponseBody> ListTransactionRulesWithHttpInfo(string userGuid, int? page = default(int?), int? recordsPerPage = default(int?), int operationIndex = 0)
        {
            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling TransactionRulesApi->ListTransactionRules");
            }

            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (recordsPerPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "records_per_page", recordsPerPage));
            }

            localVarRequestOptions.Operation = "TransactionRulesApi.ListTransactionRules";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TransactionRulesResponseBody>("/users/{user_guid}/transaction_rules", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTransactionRules", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List transaction rules Use this endpoint to read the attributes of all existing transaction rules belonging to the user.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="page">Results are paginated. Specify current page. (optional)</param>
        /// <param name="recordsPerPage">This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionRulesResponseBody</returns>
        public async System.Threading.Tasks.Task<TransactionRulesResponseBody> ListTransactionRulesAsync(string userGuid, int? page = default(int?), int? recordsPerPage = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MX.Platform.CSharp.Client.ApiResponse<TransactionRulesResponseBody> localVarResponse = await ListTransactionRulesWithHttpInfoAsync(userGuid, page, recordsPerPage, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List transaction rules Use this endpoint to read the attributes of all existing transaction rules belonging to the user.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="page">Results are paginated. Specify current page. (optional)</param>
        /// <param name="recordsPerPage">This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionRulesResponseBody)</returns>
        public async System.Threading.Tasks.Task<MX.Platform.CSharp.Client.ApiResponse<TransactionRulesResponseBody>> ListTransactionRulesWithHttpInfoAsync(string userGuid, int? page = default(int?), int? recordsPerPage = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling TransactionRulesApi->ListTransactionRules");
            }


            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (recordsPerPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "records_per_page", recordsPerPage));
            }

            localVarRequestOptions.Operation = "TransactionRulesApi.ListTransactionRules";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<TransactionRulesResponseBody>("/users/{user_guid}/transaction_rules", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTransactionRules", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read transaction rule Use this endpoint to read the attributes of an existing transaction rule based on the rule’s unique GUID.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TransactionRuleResponseBody</returns>
        public TransactionRuleResponseBody ReadTransactionRule(string transactionRuleGuid, string userGuid, int operationIndex = 0)
        {
            MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody> localVarResponse = ReadTransactionRuleWithHttpInfo(transactionRuleGuid, userGuid);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read transaction rule Use this endpoint to read the attributes of an existing transaction rule based on the rule’s unique GUID.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TransactionRuleResponseBody</returns>
        public MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody> ReadTransactionRuleWithHttpInfo(string transactionRuleGuid, string userGuid, int operationIndex = 0)
        {
            // verify the required parameter 'transactionRuleGuid' is set
            if (transactionRuleGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'transactionRuleGuid' when calling TransactionRulesApi->ReadTransactionRule");
            }

            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling TransactionRulesApi->ReadTransactionRule");
            }

            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("transaction_rule_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(transactionRuleGuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter

            localVarRequestOptions.Operation = "TransactionRulesApi.ReadTransactionRule";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TransactionRuleResponseBody>("/users/{user_guid}/transaction_rules/{transaction_rule_guid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadTransactionRule", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read transaction rule Use this endpoint to read the attributes of an existing transaction rule based on the rule’s unique GUID.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionRuleResponseBody</returns>
        public async System.Threading.Tasks.Task<TransactionRuleResponseBody> ReadTransactionRuleAsync(string transactionRuleGuid, string userGuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody> localVarResponse = await ReadTransactionRuleWithHttpInfoAsync(transactionRuleGuid, userGuid, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read transaction rule Use this endpoint to read the attributes of an existing transaction rule based on the rule’s unique GUID.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionRuleResponseBody)</returns>
        public async System.Threading.Tasks.Task<MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody>> ReadTransactionRuleWithHttpInfoAsync(string transactionRuleGuid, string userGuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'transactionRuleGuid' is set
            if (transactionRuleGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'transactionRuleGuid' when calling TransactionRulesApi->ReadTransactionRule");
            }

            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling TransactionRulesApi->ReadTransactionRule");
            }


            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("transaction_rule_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(transactionRuleGuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter

            localVarRequestOptions.Operation = "TransactionRulesApi.ReadTransactionRule";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<TransactionRuleResponseBody>("/users/{user_guid}/transaction_rules/{transaction_rule_guid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReadTransactionRule", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update transaction rule Use this endpoint to update the attributes of a specific transaction rule based on its unique GUID. The API will respond with the updated transaction_rule object. Any attributes not provided will be left unchanged.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleUpdateRequestBody">TransactionRule object to be updated</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TransactionRuleResponseBody</returns>
        public TransactionRuleResponseBody UpdateTransactionRule(string transactionRuleGuid, string userGuid, TransactionRuleUpdateRequestBody transactionRuleUpdateRequestBody, int operationIndex = 0)
        {
            MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody> localVarResponse = UpdateTransactionRuleWithHttpInfo(transactionRuleGuid, userGuid, transactionRuleUpdateRequestBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update transaction rule Use this endpoint to update the attributes of a specific transaction rule based on its unique GUID. The API will respond with the updated transaction_rule object. Any attributes not provided will be left unchanged.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleUpdateRequestBody">TransactionRule object to be updated</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TransactionRuleResponseBody</returns>
        public MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody> UpdateTransactionRuleWithHttpInfo(string transactionRuleGuid, string userGuid, TransactionRuleUpdateRequestBody transactionRuleUpdateRequestBody, int operationIndex = 0)
        {
            // verify the required parameter 'transactionRuleGuid' is set
            if (transactionRuleGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'transactionRuleGuid' when calling TransactionRulesApi->UpdateTransactionRule");
            }

            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling TransactionRulesApi->UpdateTransactionRule");
            }

            // verify the required parameter 'transactionRuleUpdateRequestBody' is set
            if (transactionRuleUpdateRequestBody == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'transactionRuleUpdateRequestBody' when calling TransactionRulesApi->UpdateTransactionRule");
            }

            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("transaction_rule_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(transactionRuleGuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            localVarRequestOptions.Data = transactionRuleUpdateRequestBody;

            localVarRequestOptions.Operation = "TransactionRulesApi.UpdateTransactionRule";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<TransactionRuleResponseBody>("/users/{user_guid}/transaction_rules/{transaction_rule_guid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateTransactionRule", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update transaction rule Use this endpoint to update the attributes of a specific transaction rule based on its unique GUID. The API will respond with the updated transaction_rule object. Any attributes not provided will be left unchanged.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleUpdateRequestBody">TransactionRule object to be updated</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TransactionRuleResponseBody</returns>
        public async System.Threading.Tasks.Task<TransactionRuleResponseBody> UpdateTransactionRuleAsync(string transactionRuleGuid, string userGuid, TransactionRuleUpdateRequestBody transactionRuleUpdateRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody> localVarResponse = await UpdateTransactionRuleWithHttpInfoAsync(transactionRuleGuid, userGuid, transactionRuleUpdateRequestBody, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update transaction rule Use this endpoint to update the attributes of a specific transaction rule based on its unique GUID. The API will respond with the updated transaction_rule object. Any attributes not provided will be left unchanged.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionRuleGuid">The unique id for a &#x60;transaction_rule&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="transactionRuleUpdateRequestBody">TransactionRule object to be updated</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TransactionRuleResponseBody)</returns>
        public async System.Threading.Tasks.Task<MX.Platform.CSharp.Client.ApiResponse<TransactionRuleResponseBody>> UpdateTransactionRuleWithHttpInfoAsync(string transactionRuleGuid, string userGuid, TransactionRuleUpdateRequestBody transactionRuleUpdateRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'transactionRuleGuid' is set
            if (transactionRuleGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'transactionRuleGuid' when calling TransactionRulesApi->UpdateTransactionRule");
            }

            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling TransactionRulesApi->UpdateTransactionRule");
            }

            // verify the required parameter 'transactionRuleUpdateRequestBody' is set
            if (transactionRuleUpdateRequestBody == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'transactionRuleUpdateRequestBody' when calling TransactionRulesApi->UpdateTransactionRule");
            }


            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("transaction_rule_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(transactionRuleGuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            localVarRequestOptions.Data = transactionRuleUpdateRequestBody;

            localVarRequestOptions.Operation = "TransactionRulesApi.UpdateTransactionRule";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<TransactionRuleResponseBody>("/users/{user_guid}/transaction_rules/{transaction_rule_guid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateTransactionRule", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
