/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using MX.Platform.CSharp.Client;
using MX.Platform.CSharp.Model;

namespace MX.Platform.CSharp.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWidgetsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// (Deprecated) Request connect widget URL
        /// </summary>
        /// <remarks>
        /// This endpoint will return a URL for an embeddable version of MX Connect.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="connectWidgetRequestBody">Optional config options for WebView (is_mobile_webview, current_institution_code, current_member_guid, update_credentials)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConnectWidgetResponseBody</returns>
        [Obsolete]
        ConnectWidgetResponseBody RequestConnectWidgetURL(string userGuid, ConnectWidgetRequestBody connectWidgetRequestBody, int operationIndex = 0);

        /// <summary>
        /// (Deprecated) Request connect widget URL
        /// </summary>
        /// <remarks>
        /// This endpoint will return a URL for an embeddable version of MX Connect.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="connectWidgetRequestBody">Optional config options for WebView (is_mobile_webview, current_institution_code, current_member_guid, update_credentials)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConnectWidgetResponseBody</returns>
        [Obsolete]
        ApiResponse<ConnectWidgetResponseBody> RequestConnectWidgetURLWithHttpInfo(string userGuid, ConnectWidgetRequestBody connectWidgetRequestBody, int operationIndex = 0);
        /// <summary>
        /// Request oauth window uri
        /// </summary>
        /// <remarks>
        /// This endpoint will generate an &#x60;oauth_window_uri&#x60; for the specified &#x60;member&#x60;.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="memberGuid">The unique id for a &#x60;member&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="clientRedirectUrl">A URL that MX will redirect to at the end of OAuth with additional query parameters. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="enableApp2app">This indicates whether OAuth app2app behavior is enabled for institutions that support it. Defaults to &#x60;true&#x60;. When set to &#x60;false&#x60;, any &#x60;oauth_window_uri&#x60; generated will **not** direct the end user to the institution&#39;s mobile application. This setting is not persistent. This setting currently only affects Chase institutions. (optional)</param>
        /// <param name="referralSource">Must be either &#x60;BROWSER&#x60; or &#x60;APP&#x60; depending on the implementation. Defaults to &#x60;BROWSER&#x60;. (optional)</param>
        /// <param name="skipAggregation">Setting this parameter to &#x60;true&#x60; will prevent the member from automatically aggregating after being redirected from the authorization page. (optional)</param>
        /// <param name="uiMessageWebviewUrlScheme">A scheme for routing the user back to the application state they were previously in. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OAuthWindowResponseBody</returns>
        OAuthWindowResponseBody RequestOAuthWindowURI(string memberGuid, string userGuid, string? clientRedirectUrl = default(string?), string? enableApp2app = default(string?), string? referralSource = default(string?), bool? skipAggregation = default(bool?), string? uiMessageWebviewUrlScheme = default(string?), int operationIndex = 0);

        /// <summary>
        /// Request oauth window uri
        /// </summary>
        /// <remarks>
        /// This endpoint will generate an &#x60;oauth_window_uri&#x60; for the specified &#x60;member&#x60;.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="memberGuid">The unique id for a &#x60;member&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="clientRedirectUrl">A URL that MX will redirect to at the end of OAuth with additional query parameters. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="enableApp2app">This indicates whether OAuth app2app behavior is enabled for institutions that support it. Defaults to &#x60;true&#x60;. When set to &#x60;false&#x60;, any &#x60;oauth_window_uri&#x60; generated will **not** direct the end user to the institution&#39;s mobile application. This setting is not persistent. This setting currently only affects Chase institutions. (optional)</param>
        /// <param name="referralSource">Must be either &#x60;BROWSER&#x60; or &#x60;APP&#x60; depending on the implementation. Defaults to &#x60;BROWSER&#x60;. (optional)</param>
        /// <param name="skipAggregation">Setting this parameter to &#x60;true&#x60; will prevent the member from automatically aggregating after being redirected from the authorization page. (optional)</param>
        /// <param name="uiMessageWebviewUrlScheme">A scheme for routing the user back to the application state they were previously in. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OAuthWindowResponseBody</returns>
        ApiResponse<OAuthWindowResponseBody> RequestOAuthWindowURIWithHttpInfo(string memberGuid, string userGuid, string? clientRedirectUrl = default(string?), string? enableApp2app = default(string?), string? referralSource = default(string?), bool? skipAggregation = default(bool?), string? uiMessageWebviewUrlScheme = default(string?), int operationIndex = 0);
        /// <summary>
        /// Request widget URL
        /// </summary>
        /// <remarks>
        /// Get an embeddable URL for integrating a widget into your website or app. The URL expires after ten minutes or upon first use, whichever occurs first. You&#39;ll need to obtain a new URL each time the page loads or reloads.  Include the &#x60;widget_type&#x60; in the request body to specify which widget you want to embed—the Connect Widget, a Personal Financial Management widget, or an Insights widget. Some request parameters are specific to certain widget types.  To embed the Connect Widget, set &#x60;widget_type&#x60; to &#x60;connect_widget&#x60;.  For a full list of available widget types, see [Widget Types](/api-reference/platform-api/reference/widgets#widget-types). 
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="widgetRequestBody">The widget url configuration options.</param>
        /// <param name="acceptLanguage">The desired language of the widget. (optional)</param>
        /// <param name="X_CALLBACK_PAYLOAD">The base64 encoded string defined in this header will be returned in the [Member](/resources/webhooks/member/) and [Member Data Updated](/resources/webhooks/member#member-data-updated) webhooks. This allows you to trace user interactions and workflows initiated externally and internally in the MX Platform. Max 1024 characters. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>WidgetResponseBody</returns>
        WidgetResponseBody RequestWidgetURL(string userGuid, WidgetRequestBody widgetRequestBody, string? acceptLanguage = default(string?), string? X_CALLBACK_PAYLOAD = default(string?), int operationIndex = 0);

        /// <summary>
        /// Request widget URL
        /// </summary>
        /// <remarks>
        /// Get an embeddable URL for integrating a widget into your website or app. The URL expires after ten minutes or upon first use, whichever occurs first. You&#39;ll need to obtain a new URL each time the page loads or reloads.  Include the &#x60;widget_type&#x60; in the request body to specify which widget you want to embed—the Connect Widget, a Personal Financial Management widget, or an Insights widget. Some request parameters are specific to certain widget types.  To embed the Connect Widget, set &#x60;widget_type&#x60; to &#x60;connect_widget&#x60;.  For a full list of available widget types, see [Widget Types](/api-reference/platform-api/reference/widgets#widget-types). 
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="widgetRequestBody">The widget url configuration options.</param>
        /// <param name="acceptLanguage">The desired language of the widget. (optional)</param>
        /// <param name="X_CALLBACK_PAYLOAD">The base64 encoded string defined in this header will be returned in the [Member](/resources/webhooks/member/) and [Member Data Updated](/resources/webhooks/member#member-data-updated) webhooks. This allows you to trace user interactions and workflows initiated externally and internally in the MX Platform. Max 1024 characters. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of WidgetResponseBody</returns>
        ApiResponse<WidgetResponseBody> RequestWidgetURLWithHttpInfo(string userGuid, WidgetRequestBody widgetRequestBody, string? acceptLanguage = default(string?), string? X_CALLBACK_PAYLOAD = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWidgetsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// (Deprecated) Request connect widget URL
        /// </summary>
        /// <remarks>
        /// This endpoint will return a URL for an embeddable version of MX Connect.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="connectWidgetRequestBody">Optional config options for WebView (is_mobile_webview, current_institution_code, current_member_guid, update_credentials)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConnectWidgetResponseBody</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ConnectWidgetResponseBody> RequestConnectWidgetURLAsync(string userGuid, ConnectWidgetRequestBody connectWidgetRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// (Deprecated) Request connect widget URL
        /// </summary>
        /// <remarks>
        /// This endpoint will return a URL for an embeddable version of MX Connect.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="connectWidgetRequestBody">Optional config options for WebView (is_mobile_webview, current_institution_code, current_member_guid, update_credentials)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConnectWidgetResponseBody)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<ConnectWidgetResponseBody>> RequestConnectWidgetURLWithHttpInfoAsync(string userGuid, ConnectWidgetRequestBody connectWidgetRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Request oauth window uri
        /// </summary>
        /// <remarks>
        /// This endpoint will generate an &#x60;oauth_window_uri&#x60; for the specified &#x60;member&#x60;.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="memberGuid">The unique id for a &#x60;member&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="clientRedirectUrl">A URL that MX will redirect to at the end of OAuth with additional query parameters. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="enableApp2app">This indicates whether OAuth app2app behavior is enabled for institutions that support it. Defaults to &#x60;true&#x60;. When set to &#x60;false&#x60;, any &#x60;oauth_window_uri&#x60; generated will **not** direct the end user to the institution&#39;s mobile application. This setting is not persistent. This setting currently only affects Chase institutions. (optional)</param>
        /// <param name="referralSource">Must be either &#x60;BROWSER&#x60; or &#x60;APP&#x60; depending on the implementation. Defaults to &#x60;BROWSER&#x60;. (optional)</param>
        /// <param name="skipAggregation">Setting this parameter to &#x60;true&#x60; will prevent the member from automatically aggregating after being redirected from the authorization page. (optional)</param>
        /// <param name="uiMessageWebviewUrlScheme">A scheme for routing the user back to the application state they were previously in. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OAuthWindowResponseBody</returns>
        System.Threading.Tasks.Task<OAuthWindowResponseBody> RequestOAuthWindowURIAsync(string memberGuid, string userGuid, string? clientRedirectUrl = default(string?), string? enableApp2app = default(string?), string? referralSource = default(string?), bool? skipAggregation = default(bool?), string? uiMessageWebviewUrlScheme = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Request oauth window uri
        /// </summary>
        /// <remarks>
        /// This endpoint will generate an &#x60;oauth_window_uri&#x60; for the specified &#x60;member&#x60;.
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="memberGuid">The unique id for a &#x60;member&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="clientRedirectUrl">A URL that MX will redirect to at the end of OAuth with additional query parameters. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="enableApp2app">This indicates whether OAuth app2app behavior is enabled for institutions that support it. Defaults to &#x60;true&#x60;. When set to &#x60;false&#x60;, any &#x60;oauth_window_uri&#x60; generated will **not** direct the end user to the institution&#39;s mobile application. This setting is not persistent. This setting currently only affects Chase institutions. (optional)</param>
        /// <param name="referralSource">Must be either &#x60;BROWSER&#x60; or &#x60;APP&#x60; depending on the implementation. Defaults to &#x60;BROWSER&#x60;. (optional)</param>
        /// <param name="skipAggregation">Setting this parameter to &#x60;true&#x60; will prevent the member from automatically aggregating after being redirected from the authorization page. (optional)</param>
        /// <param name="uiMessageWebviewUrlScheme">A scheme for routing the user back to the application state they were previously in. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OAuthWindowResponseBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<OAuthWindowResponseBody>> RequestOAuthWindowURIWithHttpInfoAsync(string memberGuid, string userGuid, string? clientRedirectUrl = default(string?), string? enableApp2app = default(string?), string? referralSource = default(string?), bool? skipAggregation = default(bool?), string? uiMessageWebviewUrlScheme = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Request widget URL
        /// </summary>
        /// <remarks>
        /// Get an embeddable URL for integrating a widget into your website or app. The URL expires after ten minutes or upon first use, whichever occurs first. You&#39;ll need to obtain a new URL each time the page loads or reloads.  Include the &#x60;widget_type&#x60; in the request body to specify which widget you want to embed—the Connect Widget, a Personal Financial Management widget, or an Insights widget. Some request parameters are specific to certain widget types.  To embed the Connect Widget, set &#x60;widget_type&#x60; to &#x60;connect_widget&#x60;.  For a full list of available widget types, see [Widget Types](/api-reference/platform-api/reference/widgets#widget-types). 
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="widgetRequestBody">The widget url configuration options.</param>
        /// <param name="acceptLanguage">The desired language of the widget. (optional)</param>
        /// <param name="X_CALLBACK_PAYLOAD">The base64 encoded string defined in this header will be returned in the [Member](/resources/webhooks/member/) and [Member Data Updated](/resources/webhooks/member#member-data-updated) webhooks. This allows you to trace user interactions and workflows initiated externally and internally in the MX Platform. Max 1024 characters. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WidgetResponseBody</returns>
        System.Threading.Tasks.Task<WidgetResponseBody> RequestWidgetURLAsync(string userGuid, WidgetRequestBody widgetRequestBody, string? acceptLanguage = default(string?), string? X_CALLBACK_PAYLOAD = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Request widget URL
        /// </summary>
        /// <remarks>
        /// Get an embeddable URL for integrating a widget into your website or app. The URL expires after ten minutes or upon first use, whichever occurs first. You&#39;ll need to obtain a new URL each time the page loads or reloads.  Include the &#x60;widget_type&#x60; in the request body to specify which widget you want to embed—the Connect Widget, a Personal Financial Management widget, or an Insights widget. Some request parameters are specific to certain widget types.  To embed the Connect Widget, set &#x60;widget_type&#x60; to &#x60;connect_widget&#x60;.  For a full list of available widget types, see [Widget Types](/api-reference/platform-api/reference/widgets#widget-types). 
        /// </remarks>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="widgetRequestBody">The widget url configuration options.</param>
        /// <param name="acceptLanguage">The desired language of the widget. (optional)</param>
        /// <param name="X_CALLBACK_PAYLOAD">The base64 encoded string defined in this header will be returned in the [Member](/resources/webhooks/member/) and [Member Data Updated](/resources/webhooks/member#member-data-updated) webhooks. This allows you to trace user interactions and workflows initiated externally and internally in the MX Platform. Max 1024 characters. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WidgetResponseBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<WidgetResponseBody>> RequestWidgetURLWithHttpInfoAsync(string userGuid, WidgetRequestBody widgetRequestBody, string? acceptLanguage = default(string?), string? X_CALLBACK_PAYLOAD = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWidgetsApi : IWidgetsApiSync, IWidgetsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WidgetsApi : IWidgetsApi
    {
        private MX.Platform.CSharp.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WidgetsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WidgetsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WidgetsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WidgetsApi(string basePath)
        {
            this.Configuration = MX.Platform.CSharp.Client.Configuration.MergeConfigurations(
                MX.Platform.CSharp.Client.GlobalConfiguration.Instance,
                new MX.Platform.CSharp.Client.Configuration { BasePath = basePath }
            );
            this.Client = new MX.Platform.CSharp.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MX.Platform.CSharp.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = MX.Platform.CSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WidgetsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WidgetsApi(MX.Platform.CSharp.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MX.Platform.CSharp.Client.Configuration.MergeConfigurations(
                MX.Platform.CSharp.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new MX.Platform.CSharp.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MX.Platform.CSharp.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = MX.Platform.CSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WidgetsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public WidgetsApi(MX.Platform.CSharp.Client.ISynchronousClient client, MX.Platform.CSharp.Client.IAsynchronousClient asyncClient, MX.Platform.CSharp.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MX.Platform.CSharp.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public MX.Platform.CSharp.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public MX.Platform.CSharp.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MX.Platform.CSharp.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MX.Platform.CSharp.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// (Deprecated) Request connect widget URL This endpoint will return a URL for an embeddable version of MX Connect.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="connectWidgetRequestBody">Optional config options for WebView (is_mobile_webview, current_institution_code, current_member_guid, update_credentials)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConnectWidgetResponseBody</returns>
        [Obsolete]
        public ConnectWidgetResponseBody RequestConnectWidgetURL(string userGuid, ConnectWidgetRequestBody connectWidgetRequestBody, int operationIndex = 0)
        {
            MX.Platform.CSharp.Client.ApiResponse<ConnectWidgetResponseBody> localVarResponse = RequestConnectWidgetURLWithHttpInfo(userGuid, connectWidgetRequestBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// (Deprecated) Request connect widget URL This endpoint will return a URL for an embeddable version of MX Connect.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="connectWidgetRequestBody">Optional config options for WebView (is_mobile_webview, current_institution_code, current_member_guid, update_credentials)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConnectWidgetResponseBody</returns>
        [Obsolete]
        public MX.Platform.CSharp.Client.ApiResponse<ConnectWidgetResponseBody> RequestConnectWidgetURLWithHttpInfo(string userGuid, ConnectWidgetRequestBody connectWidgetRequestBody, int operationIndex = 0)
        {
            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling WidgetsApi->RequestConnectWidgetURL");
            }

            // verify the required parameter 'connectWidgetRequestBody' is set
            if (connectWidgetRequestBody == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'connectWidgetRequestBody' when calling WidgetsApi->RequestConnectWidgetURL");
            }

            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            localVarRequestOptions.Data = connectWidgetRequestBody;

            localVarRequestOptions.Operation = "WidgetsApi.RequestConnectWidgetURL";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ConnectWidgetResponseBody>("/users/{user_guid}/connect_widget_url", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestConnectWidgetURL", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// (Deprecated) Request connect widget URL This endpoint will return a URL for an embeddable version of MX Connect.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="connectWidgetRequestBody">Optional config options for WebView (is_mobile_webview, current_institution_code, current_member_guid, update_credentials)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConnectWidgetResponseBody</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<ConnectWidgetResponseBody> RequestConnectWidgetURLAsync(string userGuid, ConnectWidgetRequestBody connectWidgetRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MX.Platform.CSharp.Client.ApiResponse<ConnectWidgetResponseBody> localVarResponse = await RequestConnectWidgetURLWithHttpInfoAsync(userGuid, connectWidgetRequestBody, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// (Deprecated) Request connect widget URL This endpoint will return a URL for an embeddable version of MX Connect.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="connectWidgetRequestBody">Optional config options for WebView (is_mobile_webview, current_institution_code, current_member_guid, update_credentials)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConnectWidgetResponseBody)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<MX.Platform.CSharp.Client.ApiResponse<ConnectWidgetResponseBody>> RequestConnectWidgetURLWithHttpInfoAsync(string userGuid, ConnectWidgetRequestBody connectWidgetRequestBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling WidgetsApi->RequestConnectWidgetURL");
            }

            // verify the required parameter 'connectWidgetRequestBody' is set
            if (connectWidgetRequestBody == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'connectWidgetRequestBody' when calling WidgetsApi->RequestConnectWidgetURL");
            }


            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            localVarRequestOptions.Data = connectWidgetRequestBody;

            localVarRequestOptions.Operation = "WidgetsApi.RequestConnectWidgetURL";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ConnectWidgetResponseBody>("/users/{user_guid}/connect_widget_url", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestConnectWidgetURL", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Request oauth window uri This endpoint will generate an &#x60;oauth_window_uri&#x60; for the specified &#x60;member&#x60;.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="memberGuid">The unique id for a &#x60;member&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="clientRedirectUrl">A URL that MX will redirect to at the end of OAuth with additional query parameters. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="enableApp2app">This indicates whether OAuth app2app behavior is enabled for institutions that support it. Defaults to &#x60;true&#x60;. When set to &#x60;false&#x60;, any &#x60;oauth_window_uri&#x60; generated will **not** direct the end user to the institution&#39;s mobile application. This setting is not persistent. This setting currently only affects Chase institutions. (optional)</param>
        /// <param name="referralSource">Must be either &#x60;BROWSER&#x60; or &#x60;APP&#x60; depending on the implementation. Defaults to &#x60;BROWSER&#x60;. (optional)</param>
        /// <param name="skipAggregation">Setting this parameter to &#x60;true&#x60; will prevent the member from automatically aggregating after being redirected from the authorization page. (optional)</param>
        /// <param name="uiMessageWebviewUrlScheme">A scheme for routing the user back to the application state they were previously in. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OAuthWindowResponseBody</returns>
        public OAuthWindowResponseBody RequestOAuthWindowURI(string memberGuid, string userGuid, string? clientRedirectUrl = default(string?), string? enableApp2app = default(string?), string? referralSource = default(string?), bool? skipAggregation = default(bool?), string? uiMessageWebviewUrlScheme = default(string?), int operationIndex = 0)
        {
            MX.Platform.CSharp.Client.ApiResponse<OAuthWindowResponseBody> localVarResponse = RequestOAuthWindowURIWithHttpInfo(memberGuid, userGuid, clientRedirectUrl, enableApp2app, referralSource, skipAggregation, uiMessageWebviewUrlScheme);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Request oauth window uri This endpoint will generate an &#x60;oauth_window_uri&#x60; for the specified &#x60;member&#x60;.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="memberGuid">The unique id for a &#x60;member&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="clientRedirectUrl">A URL that MX will redirect to at the end of OAuth with additional query parameters. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="enableApp2app">This indicates whether OAuth app2app behavior is enabled for institutions that support it. Defaults to &#x60;true&#x60;. When set to &#x60;false&#x60;, any &#x60;oauth_window_uri&#x60; generated will **not** direct the end user to the institution&#39;s mobile application. This setting is not persistent. This setting currently only affects Chase institutions. (optional)</param>
        /// <param name="referralSource">Must be either &#x60;BROWSER&#x60; or &#x60;APP&#x60; depending on the implementation. Defaults to &#x60;BROWSER&#x60;. (optional)</param>
        /// <param name="skipAggregation">Setting this parameter to &#x60;true&#x60; will prevent the member from automatically aggregating after being redirected from the authorization page. (optional)</param>
        /// <param name="uiMessageWebviewUrlScheme">A scheme for routing the user back to the application state they were previously in. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OAuthWindowResponseBody</returns>
        public MX.Platform.CSharp.Client.ApiResponse<OAuthWindowResponseBody> RequestOAuthWindowURIWithHttpInfo(string memberGuid, string userGuid, string? clientRedirectUrl = default(string?), string? enableApp2app = default(string?), string? referralSource = default(string?), bool? skipAggregation = default(bool?), string? uiMessageWebviewUrlScheme = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'memberGuid' is set
            if (memberGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'memberGuid' when calling WidgetsApi->RequestOAuthWindowURI");
            }

            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling WidgetsApi->RequestOAuthWindowURI");
            }

            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("member_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(memberGuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            if (clientRedirectUrl != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "client_redirect_url", clientRedirectUrl));
            }
            if (enableApp2app != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "enable_app2app", enableApp2app));
            }
            if (referralSource != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "referral_source", referralSource));
            }
            if (skipAggregation != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "skip_aggregation", skipAggregation));
            }
            if (uiMessageWebviewUrlScheme != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "ui_message_webview_url_scheme", uiMessageWebviewUrlScheme));
            }

            localVarRequestOptions.Operation = "WidgetsApi.RequestOAuthWindowURI";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<OAuthWindowResponseBody>("/users/{user_guid}/members/{member_guid}/oauth_window_uri", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestOAuthWindowURI", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Request oauth window uri This endpoint will generate an &#x60;oauth_window_uri&#x60; for the specified &#x60;member&#x60;.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="memberGuid">The unique id for a &#x60;member&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="clientRedirectUrl">A URL that MX will redirect to at the end of OAuth with additional query parameters. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="enableApp2app">This indicates whether OAuth app2app behavior is enabled for institutions that support it. Defaults to &#x60;true&#x60;. When set to &#x60;false&#x60;, any &#x60;oauth_window_uri&#x60; generated will **not** direct the end user to the institution&#39;s mobile application. This setting is not persistent. This setting currently only affects Chase institutions. (optional)</param>
        /// <param name="referralSource">Must be either &#x60;BROWSER&#x60; or &#x60;APP&#x60; depending on the implementation. Defaults to &#x60;BROWSER&#x60;. (optional)</param>
        /// <param name="skipAggregation">Setting this parameter to &#x60;true&#x60; will prevent the member from automatically aggregating after being redirected from the authorization page. (optional)</param>
        /// <param name="uiMessageWebviewUrlScheme">A scheme for routing the user back to the application state they were previously in. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OAuthWindowResponseBody</returns>
        public async System.Threading.Tasks.Task<OAuthWindowResponseBody> RequestOAuthWindowURIAsync(string memberGuid, string userGuid, string? clientRedirectUrl = default(string?), string? enableApp2app = default(string?), string? referralSource = default(string?), bool? skipAggregation = default(bool?), string? uiMessageWebviewUrlScheme = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MX.Platform.CSharp.Client.ApiResponse<OAuthWindowResponseBody> localVarResponse = await RequestOAuthWindowURIWithHttpInfoAsync(memberGuid, userGuid, clientRedirectUrl, enableApp2app, referralSource, skipAggregation, uiMessageWebviewUrlScheme, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Request oauth window uri This endpoint will generate an &#x60;oauth_window_uri&#x60; for the specified &#x60;member&#x60;.
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="memberGuid">The unique id for a &#x60;member&#x60;.</param>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="clientRedirectUrl">A URL that MX will redirect to at the end of OAuth with additional query parameters. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="enableApp2app">This indicates whether OAuth app2app behavior is enabled for institutions that support it. Defaults to &#x60;true&#x60;. When set to &#x60;false&#x60;, any &#x60;oauth_window_uri&#x60; generated will **not** direct the end user to the institution&#39;s mobile application. This setting is not persistent. This setting currently only affects Chase institutions. (optional)</param>
        /// <param name="referralSource">Must be either &#x60;BROWSER&#x60; or &#x60;APP&#x60; depending on the implementation. Defaults to &#x60;BROWSER&#x60;. (optional)</param>
        /// <param name="skipAggregation">Setting this parameter to &#x60;true&#x60; will prevent the member from automatically aggregating after being redirected from the authorization page. (optional)</param>
        /// <param name="uiMessageWebviewUrlScheme">A scheme for routing the user back to the application state they were previously in. Only available with &#x60;referral_source&#x3D;APP&#x60;. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OAuthWindowResponseBody)</returns>
        public async System.Threading.Tasks.Task<MX.Platform.CSharp.Client.ApiResponse<OAuthWindowResponseBody>> RequestOAuthWindowURIWithHttpInfoAsync(string memberGuid, string userGuid, string? clientRedirectUrl = default(string?), string? enableApp2app = default(string?), string? referralSource = default(string?), bool? skipAggregation = default(bool?), string? uiMessageWebviewUrlScheme = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'memberGuid' is set
            if (memberGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'memberGuid' when calling WidgetsApi->RequestOAuthWindowURI");
            }

            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling WidgetsApi->RequestOAuthWindowURI");
            }


            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("member_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(memberGuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            if (clientRedirectUrl != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "client_redirect_url", clientRedirectUrl));
            }
            if (enableApp2app != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "enable_app2app", enableApp2app));
            }
            if (referralSource != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "referral_source", referralSource));
            }
            if (skipAggregation != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "skip_aggregation", skipAggregation));
            }
            if (uiMessageWebviewUrlScheme != null)
            {
                localVarRequestOptions.QueryParameters.Add(MX.Platform.CSharp.Client.ClientUtils.ParameterToMultiMap("", "ui_message_webview_url_scheme", uiMessageWebviewUrlScheme));
            }

            localVarRequestOptions.Operation = "WidgetsApi.RequestOAuthWindowURI";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<OAuthWindowResponseBody>("/users/{user_guid}/members/{member_guid}/oauth_window_uri", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestOAuthWindowURI", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Request widget URL Get an embeddable URL for integrating a widget into your website or app. The URL expires after ten minutes or upon first use, whichever occurs first. You&#39;ll need to obtain a new URL each time the page loads or reloads.  Include the &#x60;widget_type&#x60; in the request body to specify which widget you want to embed—the Connect Widget, a Personal Financial Management widget, or an Insights widget. Some request parameters are specific to certain widget types.  To embed the Connect Widget, set &#x60;widget_type&#x60; to &#x60;connect_widget&#x60;.  For a full list of available widget types, see [Widget Types](/api-reference/platform-api/reference/widgets#widget-types). 
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="widgetRequestBody">The widget url configuration options.</param>
        /// <param name="acceptLanguage">The desired language of the widget. (optional)</param>
        /// <param name="X_CALLBACK_PAYLOAD">The base64 encoded string defined in this header will be returned in the [Member](/resources/webhooks/member/) and [Member Data Updated](/resources/webhooks/member#member-data-updated) webhooks. This allows you to trace user interactions and workflows initiated externally and internally in the MX Platform. Max 1024 characters. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>WidgetResponseBody</returns>
        public WidgetResponseBody RequestWidgetURL(string userGuid, WidgetRequestBody widgetRequestBody, string? acceptLanguage = default(string?), string? X_CALLBACK_PAYLOAD = default(string?), int operationIndex = 0)
        {
            MX.Platform.CSharp.Client.ApiResponse<WidgetResponseBody> localVarResponse = RequestWidgetURLWithHttpInfo(userGuid, widgetRequestBody, acceptLanguage, X_CALLBACK_PAYLOAD);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Request widget URL Get an embeddable URL for integrating a widget into your website or app. The URL expires after ten minutes or upon first use, whichever occurs first. You&#39;ll need to obtain a new URL each time the page loads or reloads.  Include the &#x60;widget_type&#x60; in the request body to specify which widget you want to embed—the Connect Widget, a Personal Financial Management widget, or an Insights widget. Some request parameters are specific to certain widget types.  To embed the Connect Widget, set &#x60;widget_type&#x60; to &#x60;connect_widget&#x60;.  For a full list of available widget types, see [Widget Types](/api-reference/platform-api/reference/widgets#widget-types). 
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="widgetRequestBody">The widget url configuration options.</param>
        /// <param name="acceptLanguage">The desired language of the widget. (optional)</param>
        /// <param name="X_CALLBACK_PAYLOAD">The base64 encoded string defined in this header will be returned in the [Member](/resources/webhooks/member/) and [Member Data Updated](/resources/webhooks/member#member-data-updated) webhooks. This allows you to trace user interactions and workflows initiated externally and internally in the MX Platform. Max 1024 characters. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of WidgetResponseBody</returns>
        public MX.Platform.CSharp.Client.ApiResponse<WidgetResponseBody> RequestWidgetURLWithHttpInfo(string userGuid, WidgetRequestBody widgetRequestBody, string? acceptLanguage = default(string?), string? X_CALLBACK_PAYLOAD = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling WidgetsApi->RequestWidgetURL");
            }

            // verify the required parameter 'widgetRequestBody' is set
            if (widgetRequestBody == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'widgetRequestBody' when calling WidgetsApi->RequestWidgetURL");
            }

            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            if (acceptLanguage != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept-Language", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(acceptLanguage)); // header parameter
            }
            if (X_CALLBACK_PAYLOAD != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-CALLBACK-PAYLOAD", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(X_CALLBACK_PAYLOAD)); // header parameter
            }
            localVarRequestOptions.Data = widgetRequestBody;

            localVarRequestOptions.Operation = "WidgetsApi.RequestWidgetURL";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<WidgetResponseBody>("/users/{user_guid}/widget_urls", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestWidgetURL", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Request widget URL Get an embeddable URL for integrating a widget into your website or app. The URL expires after ten minutes or upon first use, whichever occurs first. You&#39;ll need to obtain a new URL each time the page loads or reloads.  Include the &#x60;widget_type&#x60; in the request body to specify which widget you want to embed—the Connect Widget, a Personal Financial Management widget, or an Insights widget. Some request parameters are specific to certain widget types.  To embed the Connect Widget, set &#x60;widget_type&#x60; to &#x60;connect_widget&#x60;.  For a full list of available widget types, see [Widget Types](/api-reference/platform-api/reference/widgets#widget-types). 
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="widgetRequestBody">The widget url configuration options.</param>
        /// <param name="acceptLanguage">The desired language of the widget. (optional)</param>
        /// <param name="X_CALLBACK_PAYLOAD">The base64 encoded string defined in this header will be returned in the [Member](/resources/webhooks/member/) and [Member Data Updated](/resources/webhooks/member#member-data-updated) webhooks. This allows you to trace user interactions and workflows initiated externally and internally in the MX Platform. Max 1024 characters. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WidgetResponseBody</returns>
        public async System.Threading.Tasks.Task<WidgetResponseBody> RequestWidgetURLAsync(string userGuid, WidgetRequestBody widgetRequestBody, string? acceptLanguage = default(string?), string? X_CALLBACK_PAYLOAD = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MX.Platform.CSharp.Client.ApiResponse<WidgetResponseBody> localVarResponse = await RequestWidgetURLWithHttpInfoAsync(userGuid, widgetRequestBody, acceptLanguage, X_CALLBACK_PAYLOAD, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Request widget URL Get an embeddable URL for integrating a widget into your website or app. The URL expires after ten minutes or upon first use, whichever occurs first. You&#39;ll need to obtain a new URL each time the page loads or reloads.  Include the &#x60;widget_type&#x60; in the request body to specify which widget you want to embed—the Connect Widget, a Personal Financial Management widget, or an Insights widget. Some request parameters are specific to certain widget types.  To embed the Connect Widget, set &#x60;widget_type&#x60; to &#x60;connect_widget&#x60;.  For a full list of available widget types, see [Widget Types](/api-reference/platform-api/reference/widgets#widget-types). 
        /// </summary>
        /// <exception cref="MX.Platform.CSharp.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userGuid">The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.</param>
        /// <param name="widgetRequestBody">The widget url configuration options.</param>
        /// <param name="acceptLanguage">The desired language of the widget. (optional)</param>
        /// <param name="X_CALLBACK_PAYLOAD">The base64 encoded string defined in this header will be returned in the [Member](/resources/webhooks/member/) and [Member Data Updated](/resources/webhooks/member#member-data-updated) webhooks. This allows you to trace user interactions and workflows initiated externally and internally in the MX Platform. Max 1024 characters. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WidgetResponseBody)</returns>
        public async System.Threading.Tasks.Task<MX.Platform.CSharp.Client.ApiResponse<WidgetResponseBody>> RequestWidgetURLWithHttpInfoAsync(string userGuid, WidgetRequestBody widgetRequestBody, string? acceptLanguage = default(string?), string? X_CALLBACK_PAYLOAD = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'userGuid' is set
            if (userGuid == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'userGuid' when calling WidgetsApi->RequestWidgetURL");
            }

            // verify the required parameter 'widgetRequestBody' is set
            if (widgetRequestBody == null)
            {
                throw new MX.Platform.CSharp.Client.ApiException(400, "Missing required parameter 'widgetRequestBody' when calling WidgetsApi->RequestWidgetURL");
            }


            MX.Platform.CSharp.Client.RequestOptions localVarRequestOptions = new MX.Platform.CSharp.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/vnd.mx.api.v1+json"
            };

            var localVarContentType = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MX.Platform.CSharp.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_guid", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(userGuid)); // path parameter
            if (acceptLanguage != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept-Language", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(acceptLanguage)); // header parameter
            }
            if (X_CALLBACK_PAYLOAD != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-CALLBACK-PAYLOAD", MX.Platform.CSharp.Client.ClientUtils.ParameterToString(X_CALLBACK_PAYLOAD)); // header parameter
            }
            localVarRequestOptions.Data = widgetRequestBody;

            localVarRequestOptions.Operation = "WidgetsApi.RequestWidgetURL";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + MX.Platform.CSharp.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<WidgetResponseBody>("/users/{user_guid}/widget_urls", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestWidgetURL", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
