/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MX.Platform.CSharp.Client;
using MX.Platform.CSharp.Api;
// uncomment below to import models
//using MX.Platform.CSharp.Model;

namespace MX.Platform.CSharp.Test.Api
{
    /// <summary>
    ///  Class for testing StatementsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StatementsApiTests : IDisposable
    {
        private StatementsApi instance;

        public StatementsApiTests()
        {
            instance = new StatementsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatementsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' StatementsApi
            //Assert.IsType<StatementsApi>(instance);
        }

        /// <summary>
        /// Test DownloadStatementPDF
        /// </summary>
        [Fact]
        public void DownloadStatementPDFTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string memberGuid = null;
            //string statementGuid = null;
            //string userGuid = null;
            //var response = instance.DownloadStatementPDF(memberGuid, statementGuid, userGuid);
            //Assert.IsType<System.IO.Stream>(response);
        }

        /// <summary>
        /// Test FetchStatements
        /// </summary>
        [Fact]
        public void FetchStatementsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string memberGuid = null;
            //string userGuid = null;
            //var response = instance.FetchStatements(memberGuid, userGuid);
            //Assert.IsType<MemberResponseBody>(response);
        }

        /// <summary>
        /// Test ListStatementsByMember
        /// </summary>
        [Fact]
        public void ListStatementsByMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string memberGuid = null;
            //string userGuid = null;
            //int? page = null;
            //int? recordsPerPage = null;
            //var response = instance.ListStatementsByMember(memberGuid, userGuid, page, recordsPerPage);
            //Assert.IsType<StatementsResponseBody>(response);
        }

        /// <summary>
        /// Test ReadStatementByMember
        /// </summary>
        [Fact]
        public void ReadStatementByMemberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string memberGuid = null;
            //string statementGuid = null;
            //string userGuid = null;
            //var response = instance.ReadStatementByMember(memberGuid, statementGuid, userGuid);
            //Assert.IsType<StatementResponseBody>(response);
        }
    }
}
