/*
 * MX Platform API
 *
 * The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 
 *
 * The version of the OpenAPI document: 20111101
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MX.Platform.CSharp.Client;
using MX.Platform.CSharp.Api;
// uncomment below to import models
//using MX.Platform.CSharp.Model;

namespace MX.Platform.CSharp.Test.Api
{
    /// <summary>
    ///  Class for testing TagsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TagsApiTests : IDisposable
    {
        private TagsApi instance;

        public TagsApiTests()
        {
            instance = new TagsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TagsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TagsApi
            //Assert.IsType<TagsApi>(instance);
        }

        /// <summary>
        /// Test CreateTag
        /// </summary>
        [Fact]
        public void CreateTagTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userGuid = null;
            //TagCreateRequestBody tagCreateRequestBody = null;
            //var response = instance.CreateTag(userGuid, tagCreateRequestBody);
            //Assert.IsType<TagResponseBody>(response);
        }

        /// <summary>
        /// Test DeleteTag
        /// </summary>
        [Fact]
        public void DeleteTagTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tagGuid = null;
            //string accept = null;
            //string userGuid = null;
            //instance.DeleteTag(tagGuid, accept, userGuid);
        }

        /// <summary>
        /// Test ListTags
        /// </summary>
        [Fact]
        public void ListTagsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userGuid = null;
            //int? page = null;
            //int? recordsPerPage = null;
            //var response = instance.ListTags(userGuid, page, recordsPerPage);
            //Assert.IsType<TagsResponseBody>(response);
        }

        /// <summary>
        /// Test ReadTag
        /// </summary>
        [Fact]
        public void ReadTagTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tagGuid = null;
            //string userGuid = null;
            //var response = instance.ReadTag(tagGuid, userGuid);
            //Assert.IsType<TagResponseBody>(response);
        }

        /// <summary>
        /// Test UpdateTag
        /// </summary>
        [Fact]
        public void UpdateTagTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tagGuid = null;
            //string userGuid = null;
            //TagUpdateRequestBody tagUpdateRequestBody = null;
            //var response = instance.UpdateTag(tagGuid, userGuid, tagUpdateRequestBody);
            //Assert.IsType<TagResponseBody>(response);
        }
    }
}
