name: Publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build and publish to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/MX.Platform.CSharp/MX.Platform.CSharp.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
